config/routes.rb
AsiYT::Application.routes.draw do

  root :to => "guests#index"

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session_path

  end

  resources :playlists do
    resources :clips do
      resources :ratings
    end
    resources :playlist_contributors
  end
  resources :users;

end

app/models/playlist.rb
# class Playlist < ActiveRecord::Base
#   has_one :user, :inverse_of => :playlists, :autosave => true
#   has_many :contributors, :class_name => "PlaylistContributor", :inverse_of => :playlists, :autosave => true
#   has_many :users, :inverse_of => :playlists, :through => :playlist_contributors, :autosave => true
#   has_many :clips, :inverse_of => :playlists, :autosave => true
# end
#

class Playlist < ActiveRecord::Base
  has_one :user
  has_many :contributors, :class_name => "PlaylistContributor"
  has_many :users, :through => :playlist_contributors
  has_many :clips
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]
  before_filter :verify_user_access, only: [:show, :edit, :update, :destroy]

  def show
     if @playlist.clips.empty?
       redirect_to :controller => 'clips', :action => 'show', :id => 0, :playlist_id => params[:id]
     else
      redirect_to :controller => 'clips', :action => 'show', :id => @playlist.clips.first.id, :playlist_id => @playlist.id
     end
  end

  def index
    unless params[:shared]
      @playlists = current_user.playlists
    else
      shares = PlaylistContributor.where(:user_id => current_user.id)
      unless shares.empty?
        @playlists = shares.map { |pc| Playlist.find(pc.playlist_id) }
      else
        @playlists = []
      end
    end
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user_id = current_user.id
    @playlist.save
    redirect_to controller: 'playlists', action: 'index'
  end

  def edit
  end

  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url }
      format.json { head :no_content }
    end
  end
  private

  def set_playlist
    begin
      @playlist = Playlist.find(params[:id])
    rescue
      redirect_to :controller => 'playlists', :action => 'index'
    end
  end

  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/create.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Hawks2 YT.</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Playlists</a></li>
        <li><a href="#" data-toggle="modal" data-target="#NewPlaylistModal">New playlist</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="username">
              <input type="password" class="form-control"/>
            </div>
            <button type="submit" class="btn btn-default">Log in</button>
          </form>
        </li>
        <li><a href="#">Sign up</a></li>
      </ul>
    </div>
  </div>
</nav>

<div id="wrapper" class="single-container">
  <div id="playlist-container">
    <ul>

      <% params[:playlist].each do |j| %>

          <li>
            <div class="pl-item">
              <h2 class="pl-item-name">
                <a href="playlists/single">Playlist "<%= j[1] %>" created</a>
              </h2>
            </div>
          </li>

      <% end %>

    </ul>
  </div>
</div>

app/views/playlists/index.html.erb
<div class="modal fade" id="NewPlaylistModal" tabindex="-1" role="dialog" aria-labelledby="NewPlaylistModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="NewPlaylistModalLabel">Create playlist</h4>
      </div>
      <div class="modal-body">
        <%= form_for :playlist, :html => {:class => "form-horizontal"} do |form| %>
            <fieldset>
              <div class="control-group">
                <div class="input-group">
                  <span class="input-group-addon">name</span>
                  <%= form.text_field :name, :class => 'form-control' %>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <%= form.submit :class => "btn btn-primary", 'value' => 'Add' %>
              </div>
            </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="wrapper" class="single-container">

  <% if @playlists.empty? %>
      <div class="jumbotron">
        <h1>Hello, <%= current_user.nick %>!</h1>
        <% unless params[:shared] %>
        <p><a class="btn btn-primary btn-lg" href="#" data-toggle="modal" data-target="#NewPlaylistModal" role="button">Add
          your first playlist</a></p>
        <% else %>
            <p>Nothing to see here.</p>
        <% end %>
      </div>
  <% else %>

      <div id="playlist-container">
        <ul>

          <% @playlists.each do |playlist| %>

              <li>
                <div class="pl-item">
                  <h2 class="pl-item-name">
                    <%= link_to playlist.name, playlist_path(playlist) %>
                  </h2>

                  <div class="pl-item-clips-container">
                    <ul>
                      <% playlist.clips.each do |i| %>

                          <li>
                            <div class="clip-item">
                              <a class="item-preview-img-a" href="/playlists/<%= playlist.id %>/clips/<%= i.id %>">
                                <img class="preview-img" src="<%= i.thumbnail %>" width="200"/>
                              </a>

                              <h3 class="small">
                                <a href="/playlists/<%= playlist.id %>/clips/<%= i.id %>"><%= i.title %></a>
                              </h3>

                              <h4 class="small">
                                <p><%= i.description %></p>
                              </h4>
                            </div>
                          </li>

                      <% end %>

                    </ul>
                  </div>
                </div>
              </li>

          <% end %>

        </ul>
      </div>
  <% end %>
</div>

app/views/playlists/new.html.erb
<%= form_for :playlist, url: playlists_path do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/playlists/show.html.erb
<div class="modal fade" id="EditPlaylistModal" tabindex="-1" role="dialog" aria-labelledby="EditPlaylistModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="EditPlaylistModalLabel">Rename playlist</h4>
      </div>
      <div class="modal-body">
        <%= form_for (@playlist), :html => {:class => "form-horizontal"} do |form| %>
            <fieldset>
              <div class="control-group">
                <div class="input-group">
                  <span class="input-group-addon">name</span>
                  <%= form.text_field :name, :class => 'form-control' %>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <%= form.submit :class => "btn btn-primary", 'value' => 'Rename' %>
              </div>
            </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="AddClipModal" tabindex="-1" role="dialog" aria-labelledby="AddClipModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="AddClipModalLabel">Add new clip</h4>
      </div>
      <div class="modal-body">
        <div class="input-group">
          <span class="input-group-addon">url</span>
          <input type="text" class="form-control" placeholder="http://">
        </div>
        <label>Description</label>
        <textarea class="form-control" rows="3"></textarea>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Add</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="ManageUsersModal" tabindex="-1" role="dialog" aria-labelledby="ManageUsersModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="ManageUsersModalLabel">Magage users</h4>
      </div>
      <div class="modal-body">
        <label> Invite friend</label>

        <div class="input-group">
          <input type="text" class="form-control" placeholder="username">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Add</button>
                        </span>
        </div>
        <label>Playlist viewers</label>
        <textarea class="form-control" rows="3">TODO</textarea>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Done</button>
      </div>
    </div>
  </div>
</div>

<div id="wrapper">

  <div id="sidebar-wrapper">
    <div class="sidebar-nav">
      <div class="btn-group settings-buttons">
        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#AddClipModal">
          <span class="glyphicon glyphicon glyphicon-plus"></span> Add clip
        </button>

        <div class="btn-group">
          <button type="button" class="btn btn-default" id="playlist-settings-btn" data-toggle="dropdown">
            <span class="glyphicon glyphicon glyphicon-cog"></span>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="playlist-settings-btn">
            <li><a href="#" data-toggle="modal" data-target="#EditPlaylistModal">Rename</a></li>
            <li role="presentation" class="divider"></li>
            <li role="presentation">
              <%= link_to 'Delete playlist', @playlist, method: :delete, data: {confirm: 'Are you sure you want to delete playlist with all clips?'}, 'tabindex' => '-1', 'role' => 'menuitem' %>
            </li>
          </ul>
        </div>

        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#ManageUsersModal">
          <span class="glyphicon glyphicon glyphicon-user"></span> Users
        </button>

      </div>

      <h2><%= @playlist.name %></h2>
      <ul class="sidebar-list">

        <% @playlist.clips.each do |clip| %>
            <li>
              <div class="item-list-item">
                <a class="item-preview-img-a-small" href="?v=<%= clip.id %>">
                                <span class="thumb-img-span">
                                    <img class="preview-img-small" src="<%= clip.thumbnail %>" width="100"/>
                                </span>
                  <span class="clip-name"><%= clip.title %></span>
                </a>
              </div>
            </li>

        <% end %>

      </ul>
    </div>
  </div>
  <div id="page-content-wrapper">
    <div class="page-content">
      <div class="container">
        <div class="row">
          <div class="col-md-12">

            <%
               v = params[:v]
               if v.nil? then
                 vi = @playlist.clips.first
               end
               vi ||= @playlist.clips.find(v)
               video = VideoInfo.new("http://www.youtube.com/watch?v="+vi.yt_id)
            %>

            <div class="well current-clip-container">
              <h1><%= vi.title %></h1>

              <h3><%= vi.description %></h3>
              <h5><%= video.duration %> seconds long</h5>

              <iframe width="853" height="480" src="//www.youtube.com/embed/<%= vi.yt_id %>?vq=hd720" frameborder="0" allowfullscreen></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>